/*
 * Tela.java
 *
 * Created on 20 de Outubro de 2007, 08:34
 */

package mensageiro.gui;

import javax.swing.JOptionPane;
import mensageiro.service.Mensageiro;
import mensageiro.service.MensageiroProperties;

/**
 *
 * @author  antonioh
 */
public class Tela extends javax.swing.JFrame {
    
    /** Creates new form Tela */
    public Tela() {
        initComponents();
        menuAjuda.setText("Ajuda...");
    }
    
    public void escreveLog(String msg){
        txtLog.append(msg+"\n");
    }
    
    public void exibeMensagem(String message, boolean erro) {
        int tipo = JOptionPane.INFORMATION_MESSAGE;
        if (erro) {
            tipo = JOptionPane.ERROR_MESSAGE;
        }
        JOptionPane.showMessageDialog(this,message,"Mensagem",tipo);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Código Gerado ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuSobre = new javax.swing.JMenu();
        menuAjuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mensageiro da Doutora Greice");
        jLabel1.setText("Aniversariantes:");

        jButton1.setText("Executar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExecutarAction(evt);
            }
        });

        txtLog.setColumns(20);
        txtLog.setRows(5);
        jScrollPane1.setViewportView(txtLog);

        menuSobre.setText("Sobre o Mensageiro...");
        menuAjuda.setText("Item");
        menuAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAjudaAction(evt);
            }
        });

        menuSobre.add(menuAjuda);

        jMenuBar1.add(menuSobre);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 408, Short.MAX_VALUE)
                        .add(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jButton1)
                    .add(jLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAjudaAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAjudaAction
        JOptionPane.showMessageDialog(this,"Em caso de dúvidas, ligue para o Toninho","Ajuda",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_menuAjudaAction

    private void botaoExecutarAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExecutarAction
        Mensageiro mensageiro = Mensageiro.getInstance();
        mensageiro.setTela(this);
        mensageiro.enviaEmailsFila();
    }//GEN-LAST:event_botaoExecutarAction
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }
    
    // Declaração de variáveis - não modifique//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menuAjuda;
    private javax.swing.JMenu menuSobre;
    private javax.swing.JTextArea txtLog;
    // Fim da declaração de variáveis//GEN-END:variables
    
}
